import type { ProjectTemplate } from "@/modules/project-workspace/types";

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "site-institucional",
    name: "Site Institucional",
    libraryIds: [
      "briefing",
      "contrato",
      "pagamento",
      "wireframe",
      "design",
      "aprovacao-design",
      "front",
      "seo",
      "testes",
      "publicacao",
      "entrega",
      "finalizado",
    ],
  },
  {
    id: "landing-page",
    name: "Landing Page",
    libraryIds: [
      "briefing",
      "contrato",
      "design",
      "aprovacao-design",
      "front",
      "meta-pixel",
      "testes",
      "publicacao",
      "entrega",
      "finalizado",
    ],
  },
  {
    id: "sistema-web",
    name: "Sistema Web",
    libraryIds: [
      "briefing",
      "reuniao-inicial",
      "planejamento",
      "contrato",
      "pagamento",
      "wireframe",
      "design",
      "aprovacao-design",
      "banco",
      "api",
      "back",
      "front",
      "login",
      "dashboard",
      "admin",
      "testes",
      "homologacao",
      "deploy",
      "entrega",
      "treinamento",
      "finalizado",
    ],
  },
  {
    id: "aplicativo",
    name: "Aplicativo",
    libraryIds: [
      "briefing",
      "planejamento",
      "contrato",
      "wireframe",
      "design",
      "aprovacao-design",
      "api",
      "back",
      "front",
      "login",
      "testes",
      "homologacao",
      "publicacao",
      "entrega",
      "finalizado",
    ],
  },
  {
    id: "loja-virtual",
    name: "Loja Virtual",
    libraryIds: [
      "briefing",
      "contrato",
      "pagamento",
      "design",
      "aprovacao-design",
      "front",
      "back",
      "banco",
      "integracoes",
      "seo",
      "analytics",
      "testes",
      "publicacao",
      "entrega",
      "finalizado",
    ],
  },
  {
    id: "identidade-visual",
    name: "Identidade Visual",
    libraryIds: [
      "briefing",
      "pesquisa",
      "identidade",
      "aprovacao-design",
      "entrega",
      "finalizado",
    ],
  },
  {
    id: "automacao",
    name: "Automação",
    libraryIds: [
      "briefing",
      "planejamento",
      "contrato",
      "integracoes",
      "api",
      "testes",
      "entrega",
      "treinamento",
      "finalizado",
    ],
  },
  {
    id: "crm",
    name: "CRM",
    libraryIds: [
      "briefing",
      "planejamento",
      "contrato",
      "banco",
      "api",
      "back",
      "front",
      "login",
      "dashboard",
      "integracoes",
      "testes",
      "deploy",
      "treinamento",
      "finalizado",
    ],
  },
  {
    id: "erp",
    name: "ERP",
    libraryIds: [
      "briefing",
      "reuniao-inicial",
      "planejamento",
      "contrato",
      "pagamento",
      "banco",
      "api",
      "back",
      "front",
      "admin",
      "login",
      "dashboard",
      "integracoes",
      "testes",
      "homologacao",
      "deploy",
      "treinamento",
      "suporte",
      "finalizado",
    ],
  },
];
